config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root to: 'landing#index'
  get :about, to: 'static_pages#about'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :edit, :create, :update]
  resources :topics, except: [:show] do
    resources :posts, except: [:show] do
      resources :comments, except: [:show]
    end
  end
  post :upvote, to: 'votes#upvote'
  post :downvote, to: 'votes#downvote'
  # delete :logout, to: 'sessions#destroy' (<-- used when want to remove id from session path destroy)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  paginates_per 10
  belongs_to :post
  belongs_to :user
  has_many :votes
  mount_uploader :image, ImageUploader

  def total_likes
    votes.where(value: 1).count
  end

  def total_dislikes
    votes.where(value:-1).count
  end
end


# def total_votes
#   votes.pluck(:value).sum
# end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
respond_to :js
before_action :authenticate!, only: [:create, :edit, :update, :new, :destroy]

  def index
    @post = Post.includes(:comments).find_by(id: params[:post_id])
    @topic = @post.topic
    @comments =@post.comments.order("created_at ASC").page params[:page]
    @comment = Comment.new
  end

  # def new
  #   @post = Post.find_by(id: params[:post_id])
  #   @topic = @post.topic
  #   @comment = Comment.new
  # end

  def create
    @post = Post.find_by(id: params[:post_id])
    # @topic = @post.topic
    @comment = current_user.comments.build(comment_params.merge(post_id: params[:post_id]))
    @new_comment = Comment.new

    if @comment.save
      CommentBroadcastJob.perform_later("create", @comment)
      flash.now[:success] = "You have created a new comment!"
      # redirect_to topic_post_comments_path(@topic, @post)
    else
      flash.now[:danger] = @comment.errors.full_messages
      # redirect_to new_topic_post_comment_path(@topic, @post)
    end
  end

  def edit
    @post = Post.find_by(id: params[:post_id])
    @topic = @post.topic
    @comment = Comment.find_by(id: params[:id])
    authorize @comment
  end

  def update
    @post = Post.find_by(id: params[:post_id])
    @topic = @post.topic
    @comment = Comment.find_by(id: params[:id])
    authorize @comment


    if @comment.update(comment_params)
      CommentBroadcastJob.perform_later("update", @comment)
      flash.now[:success] = "You have edited a comment!"
      # redirect_to topic_post_comments_path(@topic,@post)
    else
      flash.now[:danger] = @comment.errors.full_messages
      # redirect_to edit_topic_post_comment_path(@topic,@post, @comment)
    end
  end

  def destroy
    @post = Post.find_by(id: params[:post_id])
    @comment = Comment.find_by(id: params[:id])
    authorize = @comment

    if @comment.destroy
      CommentBroadcastJob.perform_now("destroy", @comment)
      flash.now[:success] = "You deleted a comment!"
      # redirect_to topic_post_comments_path(@post)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :image)
  end

end

app/views/comments/(deleted)edit.html.erb
<%= form_for(@comment, url: topic_post_comment_path(@topic,@post, @comment), html: { id: "comment-update-form" }) do |f| %>
<h1 class="text-center">
  Edit Comment
</h1>

  <div class="form-group">
    <h4 class="text-center"> Edit Comment Image </h4>
    <div id="preview-image">
      <% if @comment.image? %>
        <%= image_tag @comment.image, class: "img-settings img-responsive center-block" %>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.file_field :image, id: "comment_image_field", class: 'form-control image-uploader' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "comment_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Update Comment", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/comments/(deleted)new.html.erb
<%= form_for(@comment, url: topic_post_comments_path(@post), html: { id: "comment-create-form" }) do |f| %>
  <h1 class="text-center">
    Create Comment
  </h1>

  <div class="form-group">
    <h4 class="text-center"> Comment Image </h4>
    <div id="preview-image">
      <% if @comment.image? %>
        <%= image_tag @comment.image, class: "img-settings img-responsive center-block" %>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.file_field :image, id: "comment_image_field", class: 'form-control image-uploader' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "comment_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Comment", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/comments/_comment.html.erb
<div id="comment_<%=comment.id%>">
  <h3><%= comment.body %></h3>
  <%= image_tag comment.image %>
  <br>
  <div class="control-panel">
    <% if comment.user == current_user || current_user&.admin? || current_user&.moderator? %>
      <%= link_to "Edit Comment", edit_topic_post_comment_path(comment.post.topic,comment.post,comment), remote: true %>
      <br>
      <%= link_to "Delete Comment", topic_post_comment_path(comment.post.topic,comment.post,comment), method: :delete, data: { confirm: "Delete?" },remote: true %>
    <% end %>
      <br>
      <%= link_to "Like", upvote_path(comment_id: comment.id), method: :post, remote: true %>
      <br>
      <%= link_to "Dislike", downvote_path(comment_id: comment.id), method: :post, remote: true %>
      <br>
      <span> LIKES <%= comment.total_likes%>!</span>
      <br>
      <span> DISLIKES <%= comment.total_dislikes%>!</span>
  </div>
</div>

<!-- <script>
  $("comment_#{comment_id}") put inside post_channel.coffee
</script> -->

<!-- current_user.votes.find_by(comment_id: comment.id).value
if value == +1
  lin_to unlike
  else
  link_T Like
end
-->

app/views/comments/_editform.html.erb
<%= form_for(comment, url: topic_post_comment_path(comment.post.topic,comment.post, comment), remote: true, html: { id: "comment-update-form" }) do |f| %>
<h1 class="text-center">
  Edit Comment
</h1>

  <div class="form-group">
    <h4 class="text-center"> Edit Comment Image </h4>
    <div id="preview-image">
      <% if comment.image? %>
        <%= image_tag comment.image, class: "img-settings img-responsive center-block" %>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.file_field :image, id: "comment_image_field", class: 'form-control image-uploader' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "comment_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Update Comment", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<div class="create_form">
<%= form_for(comment, url: topic_post_comments_path(post), remote: true, html: { id: "comment-create-form" }) do |f| %>
  <h1 class="text-center">
    Create Comment
  </h1>

  <div class="form-group">
    <h4 class="text-center"> Comment Image </h4>
    <div id="preview-image">
      <% if @comment.image? %>
        <%= image_tag @comment.image, class: "img-settings img-responsive center-block" %>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.file_field :image, id: "comment_image_field", class: 'form-control image-uploader' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "comment_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Comment", class: "btn btn-success btn-lg" %>
  </div>
<% end %>
</div>

app/views/comments/create.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

$('#comments-form-container').html("<%=j render partial: 'comments/form', locals: { comment: @new_comment, post: @post } %>")

app/views/comments/destroy.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")


// $('#comment_<%=@comment.id%>').remove()

app/views/comments/edit.html.erb
<%= form_for(@comment, url: topic_post_comment_path(@topic,@post, @comment), html: { id: "post-update-form" }) do |f| %>
<h1 class="text-center">
  Edit Comment
</h1>

  <div class="form-group">
    <h4 class="text-center"> Edit Comment Image </h4>
    <div id="preview-image">
      <% if @comment.image? %>
        <%= image_tag @comment.image, class: "img-settings img-responsive center-block" %>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.file_field :image, id: "comment_image_field", class: 'form-control image-uploader' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "comment_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Update Comment", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/comments/edit.js.erb
$('#comment_<%= @comment.id %>').html("<%=j render partial: 'comments/editform', locals: { comment: @comment } %>")

app/views/comments/index.html.erb
<div class= "commentsection" data-id="<%=@post.id%>">
  <h1>Comments</h1>

  <div id="comments">
  <% @comments.each do |comment| %>
     <%= render partial: "comment", locals: { comment: comment, post: @post,} %>
  <% end %>
  </div>

  <div id="comments-form-container">
    <%= render partial: "form", locals: { comment: @comment, post: @post } %>
  </div>

  <div id="pagination">
    <nav>
      <%= paginate @comments %>
    </nav>
  </div>
</div>

app/views/comments/new.html.erb
<%= form_for(@comment, url: topic_post_comments_path(@post), html: { id: "comment-create-form" }) do |f| %>
  <h1 class="text-center">
    Create Comment
  </h1>

  <div class="form-group">
    <h4 class="text-center"> Comment Image </h4>
    <div id="preview-image">
      <% if @comment.image? %>
        <%= image_tag @comment.image, class: "img-settings img-responsive center-block" %>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.file_field :image, id: "comment_image_field", class: 'form-control image-uploader' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "comment_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Comment", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/comments/update.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")