config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root to: 'landing#index'
  get :about, to: 'static_pages#about'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :edit, :create, :update]
  resources :topics, except: [:show] do
    resources :posts, except: [:show] do
      resources :comments, except: [:show]
    end
  end
  post :upvote, to: 'votes#upvote'
  post :downvote, to: 'votes#downvote'
  # delete :logout, to: 'sessions#destroy' (<-- used when want to remove id from session path destroy)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_flash_messages.html.erb
<div id="flash-messages-container">
<% flash.each do |k,v| %>
  <section class="flash-messages">
    <div class="alert alert-<%=k%>">
      <button type="button" class="close" data-dismiss="alert">
        &times;
      </button>
      <div class="message">
        <%= display_message(v) %>
      </div>
    </div>
  </section>
<% end %>
</div>

app/views/partials/_header.html.erb
<div class="header">
<nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "MagicForums", root_path, class: "navbar-brand"%>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-dropdown" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse" id="header-dropdown">
        <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Topic", topics_path %></li>
        <% if current_user %>
    <li>
      <%= link_to current_user.username, edit_user_path(current_user), class: 'white shadowed link-styling' %>
    </li>

    <li>
      <%= link_to "Logout", session_path(current_user), method: :delete, class: 'white shadowed link-styling' %>
    </li>

  <% else %>

    <li>
      <%= link_to "Register", new_user_path, class: 'white shadowed link-styling' %>
    </li>

    <li>
      <%= link_to "Login", new_session_path, class: 'white shadowed link-styling' %>
    </li>
  <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>