config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root to: 'landing#index'
  get :about, to: 'static_pages#about'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :edit, :create, :update]
  resources :topics, except: [:show] do
    resources :posts, except: [:show] do
      resources :comments, except: [:show]
    end
  end
  post :upvote, to: 'votes#upvote'
  post :downvote, to: 'votes#downvote'
  # delete :logout, to: 'sessions#destroy' (<-- used when want to remove id from session path destroy)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :user
  belongs_to :topic
  mount_uploader :image, ImageUploader
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
respond_to :js
before_action :authenticate!, only: [:create, :edit, :update, :new, :destroy]

  def index
    @topic = Topic.includes(:posts).friendly.find(params[:topic_id])
    @posts = @topic.posts.order("created_at ASC")
    @post = Post.new
  end

  # def new
  #   @topic = Topic.find_by(id: params[:topic_id])
  #   @post = Post.new
  # end

  def create
    @topic = Topic.friendly.find(params[:topic_id])
    @post = current_user.posts.build(post_params.merge(topic_id: @topic.id))
    @new_post = Post.new



    if @post.save
      flash.now[:success] = "You have created a new post!"
      # redirect_to topic_posts_path(@topic)
    else
      flash.now[:danger] = @post.errors.full_messages
      # render new_topic_post_path(@topic)
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
    @topic = @post.topic
    authorize @post
  end

  def update
    @topic = Topic.find_by(id: params[:topic_id])
    @post = Post.find_by(id: params[:id])
    authorize @post

    if @post.update(post_params)
      redirect_to topic_posts_path(@topic)
    else
      redirect_to edit_topic_post_path(@topic, @post)
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    authorize @post
    @topic = @post.topic
    if @post.destroy
      redirect_to topic_posts_path(@topic)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end
end

app/views/posts/(deleted)new.html.erb
<%= form_for(@post, url: topic_posts_path(@topic,@post), html: { id: "post-create-form" }) do |f| %>

<h1 class="text-center">
  Create Post
</h1>

<div class="form-group">
    <h4 class="text-center"> Post Image </h4>
    <div id="preview-image">
      <% if @post.image? %>
        <%= image_tag @post.image, class: "img-settings img-responsive center-block" %>
      <% end %>
    </div>
  </div>

<div class="form-group">
  <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
</div>


  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "post_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Post", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(post, url: topic_posts_path(topic,post), remote: true, html: { id: "post-create-form" }) do |f| %>

<h1 class="text-center">
  Create Post
</h1>

<div class="form-group">
    <h4 class="text-center"> Post Image </h4>
    <div id="preview-image">
      <% if @post.image? %>
        <%= image_tag @post.image, class: "img-settings img-responsive center-block" %>
      <% end %>
    </div>
  </div>

<div class="form-group">
  <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
</div>


  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "post_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Post", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
  <h3><%= post.title %></h3>
  <h5><%= post.body %></h5>
    <%= image_tag post.image %>
  <br>
  <%= link_to "Comment on this post", topic_post_comments_path(@topic,post) %>
  <br>
  <%= link_to "Edit Post", edit_topic_post_path(@topic,post)%>
  <br>
  <%= link_to "Delete Post", topic_post_path(@topic,post), method: :delete, data: { confirm: "Delete?" }%>
</div>

app/views/posts/create.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

  <% if @post.persisted? %>
    $('#posts').append("<%=j render partial: 'posts/post', locals: { post: @post, topic: @post.topic } %>")
    $('#posts-form-container').html("<%=j render partial: 'posts/form', locals: { post: @new_post, topic: @topic } %>")
  <% end %>

app/views/posts/edit.html.erb
<%= form_for(@post, url: topic_post_path(@topic), html: { id: "post-update-form" }) do |f| %>
<h1 class="text-center">
  Edit Post
</h1>

<div class="form-group">
<h4 class="text-center"> Edit Image </h4>
<div id="preview-image">
  <% if @post.image? %>
    <%= image_tag @post.image, class: "img-settings img-responsive center-block" %>
  <% end %>
</div>
</div>

<div class="form-group">
<%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
</div>



  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "post_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Update Post", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<!-- <h1 class="topic-button text-center">
  <%= link_to "Create New Post", new_topic_post_path%>
</h1> -->

<div id= "posts">
<% @posts.each do |post| %>
  <%= render partial: "post", locals: {post: post, topic: @topic} %>
<% end %>
</div>

<div id= "posts-form-container">
  <%= render partial: "form", locals: {post: @post, topic: @topic} %>

</div>



<!--read more code from other, pair programming more, network more  -->

app/views/posts/new.html.erb
<%= form_for(@post, url: topic_posts_path(@topic,@post), html: { id: "post-create-form" }) do |f| %>

<h1 class="text-center">
  Create Post
</h1>

<div class="form-group">
    <h4 class="text-center"> Post Image </h4>
    <div id="preview-image">
      <% if @post.image? %>
        <%= image_tag @post.image, class: "img-settings img-responsive center-block" %>
      <% end %>
    </div>
  </div>

<div class="form-group">
  <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
</div>


  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "post_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Post", class: "btn btn-success btn-lg" %>
  </div>
<% end %>